### ISSUE TITLE
Unclear licensing situation

### ISSUE THREAD

**Issue by fwolfst** [unl/reservations#8]
Hi there,

the repository (and https://git.unl.edu/iim/unl-resource-scheduler, where I cannot register to create an issue) is missing a `LICENSE` or `COPYING` file indicating under which license the code is published.

I wanted to see the interface without being involved in any university, cloned the repository, cloned WDN adjusted the code to Ruby 2.6 and sqlite3-database and wanted to trick around within the authentication mechanism when I realised that I might not be able to use or contribute due to licensing restrictions.

Already the UNL WDN Framework Terms of use (imho should also be distributed with the respective code, but is at least linked at: https://wdn.unl.edu/unledu-web-framework-terms-use) seem pretty restrictive, so I believe there is no point in trying any further?

**Comment by jsturek** [comment]
Felix,

I'm a new developer for this and other repositories for the University of
Nebraska and I'm not sure what are licensing policies are.  I have deferred
up the chain and will get back to you.

Jeff Sturek

**Comment by jsturek** [comment]
Closing due to age of issue and no clear answer about licensing.

**Comment by fwolfst** [comment]
Okay, thanks for the notice, and very sorry for you to hear that. It's a pity that nowadays companies seem to know much about licenses with respect to their interests than educational institutions do.
